// Shared by the public page and the one-time content migration. Admin edits stay authoritative.
export const siteCopy = {
  ka: {
    heroEyebrow: "ავტომობილის ქირაობა საქართველოში", heroTitle: "შენი მოგზაურობა,", heroAccent: "შენი ტემპით.",
    heroCopy: "აირჩიე ავტომობილი, მიუთითე თარიღები და ნახე ქირაობის ღირებულება. მიღებისა და დაბრუნების ადგილი შენს გეგმებს მოარგე.",
    fleetEyebrow: "ჩვენი ავტომობილები", fleetTitle: "აირჩიე შენი ავტომობილი",
    fleetCopy: "შეადარე მოდელები, ადგილების რაოდენობა და გადაცემათა კოლოფი. თარიღების არჩევის შემდეგ ფასი სეზონისა და ქირაობის ხანგრძლივობის მიხედვით განახლდება.",
    aboutEyebrow: "GeoRentalCars", aboutTitle: "დაგეგმე მგზავრობა მარტივად",
    aboutCopy: "აირჩიე ავტომობილი და გამოგვიგზავნე ჯავშნის მოთხოვნა. ჩვენი გუნდი დაგიკავშირდება ხელმისაწვდომობისა და მიღების დეტალების დასადასტურებლად. თუ არჩევანში დახმარება გჭირდება, მოგვწერე WhatsApp-ზე ან დაგვირეკე.",
    contactEyebrow: "დაგეხმარებით არჩევანში", contactTitle: "დაგვიკავშირდი",
    contactCopy: "გაქვს კითხვა ავტომობილზე, ქირაობის პირობებზე ან მიწოდებაზე? დაგვირეკე ან მოგვწერე WhatsApp-ზე — დეტალებს ერთად შევათანხმებთ.", footerTagline: "ავტომობილის ქირაობა საქართველოში",
    search: "ნახე ავტომობილები და ფასები", cta: "ჯავშნის მოთხოვნა", conflict: "დაბრუნების თარიღი მიღების თარიღზე ადრე არ უნდა იყოს.",
    successCopy: "შენი მოთხოვნა მივიღეთ. ჯავშანი საბოლოოდ დადასტურდება ჩვენი გუნდის პასუხის შემდეგ.",
    deposit: "დეპოზიტი — ცალკე, ქირის გარდა", note: "ტარიფი განისაზღვრება მიღების სეზონითა და დღეების რაოდენობით. მიღებისა და დაბრუნების დღეები ორივე ითვლება. ხელმისაწვდომობას გუნდი დაგიდასტურებს.",
    empty: "ამ კატეგორიაში ავტომობილი ჯერ არ არის. ნახე სხვა კატეგორიები ან დაგვიკავშირდი.", base: "ზუსტი ფასისთვის აირჩიე თარიღები.", automatic: "ავტომატიკა", manual: "მექანიკა", petrol: "ბენზინი", diesel: "დიზელი",
  },
  en: {
    heroEyebrow: "Car rental in Georgia", heroTitle: "Your trip,", heroAccent: "at your pace.",
    heroCopy: "Choose a car, enter your dates and see your rental cost. Pick collection and return locations that fit your plans.",
    fleetEyebrow: "Our fleet", fleetTitle: "Find your car",
    fleetCopy: "Compare models, seats and transmissions. Select your dates to see daily rates for your season and rental duration.",
    aboutEyebrow: "GeoRentalCars", aboutTitle: "Plan your rental in a few steps",
    aboutCopy: "Choose your car and send a booking request. Our team will contact you to confirm availability and collection details. Need help choosing? Message us on WhatsApp or give us a call.",
    contactEyebrow: "Help with your rental", contactTitle: "Get in touch",
    contactCopy: "Questions about a car, rental terms or delivery? Call or message us on WhatsApp to discuss the details.", footerTagline: "Car rental in Georgia",
    search: "View cars and prices", cta: "Request a booking", conflict: "The return date cannot be before the pickup date.",
    successCopy: "We have received your request. Your booking is only confirmed once our team confirms availability.",
    deposit: "Deposit — separate from rental total", note: "The rate uses your pickup season and rental duration. Both pickup and return dates count as rental days. Our team will confirm availability.",
    empty: "No cars in this category yet. Explore another category or contact us.", base: "Select dates for your exact rate.", automatic: "Automatic", manual: "Manual", petrol: "Petrol", diesel: "Diesel",
  },
  ru: {
    heroEyebrow: "Аренда автомобилей в Грузии", heroTitle: "Ваше путешествие,", heroAccent: "ваш ритм.",
    heroCopy: "Выберите автомобиль и даты, чтобы узнать стоимость аренды. Укажите удобные места получения и возврата.",
    fleetEyebrow: "Наш автопарк", fleetTitle: "Выберите автомобиль",
    fleetCopy: "Сравните модели, количество мест и коробки передач. После выбора дат цена обновится с учётом сезона и срока аренды.",
    aboutEyebrow: "GeoRentalCars", aboutTitle: "Спланируйте аренду без лишних шагов",
    aboutCopy: "Выберите автомобиль и отправьте заявку. Мы свяжемся с вами, чтобы подтвердить наличие и детали получения. Нужна помощь с выбором? Напишите в WhatsApp или позвоните нам.",
    contactEyebrow: "Поможем с выбором", contactTitle: "Свяжитесь с нами",
    contactCopy: "Есть вопросы об автомобиле, условиях аренды или доставке? Позвоните или напишите в WhatsApp — обсудим детали.", footerTagline: "Аренда автомобилей в Грузии",
    search: "Смотреть автомобили и цены", cta: "Оставить заявку", conflict: "Дата возврата не может быть раньше даты получения.",
    successCopy: "Мы получили вашу заявку. Бронирование будет подтверждено после ответа нашей команды.",
    deposit: "Депозит — отдельно от стоимости аренды", note: "Тариф зависит от сезона получения и срока аренды. Дни получения и возврата включены в расчёт. Наличие подтвердит наша команда.",
    empty: "В этой категории пока нет автомобилей. Выберите другую категорию или свяжитесь с нами.", base: "Выберите даты для точного расчёта.", automatic: "Автомат", manual: "Механика", petrol: "Бензин", diesel: "Дизель",
  },
  ar: {
    heroEyebrow: "تأجير السيارات في جورجيا", heroTitle: "رحلتك،", heroAccent: "على راحتك.",
    heroCopy: "اختر السيارة وحدد التواريخ لمعرفة تكلفة الإيجار. اختر موقعي الاستلام والإرجاع بما يناسب خططك.",
    fleetEyebrow: "سياراتنا", fleetTitle: "اختر سيارتك",
    fleetCopy: "قارن الموديلات وعدد المقاعد وناقل الحركة. حدد التواريخ لعرض السعر اليومي حسب الموسم ومدة الإيجار.",
    aboutEyebrow: "GeoRentalCars", aboutTitle: "خطط لاستئجار سيارتك بسهولة",
    aboutCopy: "اختر السيارة وأرسل طلب الحجز. سيتواصل فريقنا معك لتأكيد التوفر وتفاصيل الاستلام. للمساعدة في الاختيار، اتصل بنا أو راسلنا عبر واتساب.",
    contactEyebrow: "نساعدك في الاختيار", contactTitle: "تواصل معنا",
    contactCopy: "لديك سؤال عن السيارة أو شروط الإيجار أو التوصيل؟ اتصل بنا أو راسلنا عبر واتساب لمناقشة التفاصيل.", footerTagline: "تأجير السيارات في جورجيا",
    search: "عرض السيارات والأسعار", cta: "طلب حجز", conflict: "لا يمكن أن يسبق تاريخ الإرجاع تاريخ الاستلام.",
    successCopy: "استلمنا طلبك. يصبح الحجز مؤكداً بعد تأكيد فريقنا للتوفر.",
    deposit: "مبلغ التأمين — منفصل عن تكلفة الإيجار", note: "يعتمد السعر على موسم الاستلام ومدة الإيجار. يُحتسب يوما الاستلام والإرجاع ضمن المدة. سيؤكد فريقنا توفر السيارة.",
    empty: "لا توجد سيارات في هذه الفئة حالياً. اختر فئة أخرى أو تواصل معنا.", base: "حدد التواريخ لمعرفة السعر الدقيق.", automatic: "أوتوماتيك", manual: "يدوي", petrol: "بنزين", diesel: "ديزل",
  },
};
